MIME-Version: 1.0
Sender: vbputz@gmail.com
Received: by 10.202.87.22 with HTTP; Tue, 28 Jul 2015 14:36:07 -0700 (PDT)
Date: Tue, 28 Jul 2015 21:36:07 +0000
Delivered-To: vbputz@gmail.com
X-Google-Sender-Auth: -a6NipAq21O71uZqOAJRV0meIf0
Message-ID: <CADsvd-RPkHogfYXWDkHypAsjXHBqZWTy-PrrGd4dUjpQnKLygw@mail.gmail.com>
Subject: travel
From: Vic Putz <vputz@nyx.net>
To: cary@thingotron.com
Content-Type: text/plain; charset=UTF-8

lhr-bwi 1-3 Jul
dub-lhr 3-4 Jul staying in Frobnitz, Snordonia

